<div class="hero-unit">
    <h1><?= $this->translate('Sample Application!') ?></h1>
    <p>US SIGNAL</p>
</div>

<div class="cta-promo ">
    <img src="http://www.terminal23.net/images/noc3.jpg"fixed-bottom" width="1200" height="80">
    <div class="content-block full-width">
        <blockquote>
            <p>
                "I don’t think you’ll find a team more committed to providing options &amp; delivering solutions than US Signal. Everyone brings a unique skill aimed at providing the best customer experience."</p>
            <cite>Rebecca, <br>US Signal</cite>
        </blockquote>
    </div>
</div>

<div class="row">
    <div class="span4">
        <h3><?= $this->translate('Passion') ?></h3>
        <p>
            “Passion. It lies in all of us. Sleeping... waiting... and though unwanted, unbidden, it will stir... open its jaws and howl. It speaks to us... guides us. Passion rules us all. And we obey. What other choice do we have? Passion is the source of our finest moments. The joy of love... the clarity of hatred... the ecstasy of grief. It hurts sometimes more than we can bear. If we could live without passion, maybe we'd know some kind of peace. But we would be hollow. Empty rooms, shuttered and dank. Without passion, we'd be truly dead.”
           <br> <cite>Joss Whedon</cite>
        </p>
    </div>

    <div class="span4">
        <h3><?php echo $this->translate('Programming') ?></h3>
        <p>
            A hobby, a passion, a desire of mine is to code. Coding for me is more than a
            career, it’s more like a boarder line obsession. If given the opportunity I can exercise my coding abilities, quickly adapt to the current
            facilitated coding architecture and serve as an asset to the team by completing task in
            efficient time and quality. Obtaining this position will mean more to me than another job,
            it will be a chance to express my passion in application development.
        </p>
   </div>

   <div class="span4">
       <h3><?php echo $this->translate('Hasenfeffer Incorporated!') ?></h3>
       <p>
           Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse malesuada adipiscing ipsum non
           vestibulum. Nam nulla risus, eleifend non volutpat at, cursus ac justo. Sed quis neque ligula, in
           fermentum velit. Aenean elit risus, vulputate ac venenatis ut, lobortis non eros.
       </p>
   </div>
</div>
